### ISSUE TITLE
"bad math expression" error on init

### ISSUE THREAD

**Issue by GeorgeGedox** [ahmubashshir/zinsults#4]
I'm trying to use this plugin as it seems to be the most complete as of now but I keep getting this error every time the shell is initialized:
```
(anon):14: bad math expression: illegal character: "
```

Using antidote as the plugin manager, tried to load only this plugin and got the same error so I don't think there are conflicts with the others I use.

ZSH version: `zsh 5.8.1 (x86_64-ubuntu-linux-gnu)`

**Comment by ahmubashshir** [comment]
can you share a minimal .zshrc with required files that can reproduce the issue?

**Comment by ahmubashshir** [comment]
nvm, figured it out...
